use_frameworks!

target 'RDSRemoteDataSolutions_Example' do
  pod 'RDSRemoteDataSolutions', :path => '../'

    pod 'KFXLog'
    pod 'KFXAdditions'

  target 'RDSRemoteDataSolutions_Tests' do
    inherit! :search_paths

  end
end
