use_frameworks!

target 'RDSRemoteDataSolutions_Example' do
  pod 'RDSRemoteDataSolutions', :path => '../'
  ## Sources
  ### If using private pods
  source 'https://bitbucket.org/kfxteam/kfxtech_cocoapodsspec'
  pod 'KFXLog'
  pod 'KFXAdditions'
  ### If using from trunk
  source 'http://github.com/Cocoapods/Specs.git'
  

  target 'RDSRemoteDataSolutions_Tests' do
    inherit! :search_paths

  end
end
